# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def pods
 pod 'Alamofire', '~> 5.4'
 pod 'RxSwift', '6.2.0'
 pod 'RxCocoa', '6.2.0'
 pod 'ReactorKit'
end

target 'UnsplashToyProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UnsplashToyProject
  pods

  target 'UnsplashToyProjectTests' do
    inherit! :search_paths
    # Pods for testing
    pods
  end

  target 'UnsplashToyProjectUITests' do
    # Pods for testing
    pods
  end

end
